spring.application.name=api

spring.datasource.url=jdbc:sqlite:api/database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.file-size-threshold=0B
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB